
build:
	@echo -en "\033[37;1;42m Build project \033[0m\n"
	@g++ -c test-queue.cpp -o test-queue.o
	@g++ test-queue.o -o test-queue
run:
	@echo -en "\033[37;1;42m Code run \033[0m\n"
	@./test-queue

clean:	
	@echo -en "\033[37;1;42m clean \033[0m\n"
	@rm -f *.o test-queue