
build:
	@echo -en "\033[37;1;42m Build project \033[0m\n"
	@g++ -c test-map.cpp -o test-map.o
	@g++ test-map.o -o test-map
run:
	@echo -en "\033[37;1;42m Code run \033[0m\n"
	@./test-map

clean:	
	@echo -en "\033[37;1;42m clean \033[0m\n"
	@rm -f *.o test-map